TEST_FOLDER = "../test/"
LOG_PATH = "../logs/log.txt"
TEMPLATES_PATH = "templates.tl"

SYMBOLIC_NAMES = {
    "TEMPLATE"                                                      : "a template",
    "TASK"                                                          : "a task",
    "TRANSPORT_ORDER_STEP"                                          : "a transportOrderStep",
    "INSTANCE"                                                      : "an instance",
    "WHITESPACE"                                                    : "a whitespace",
    "NEW_LINE"                                                      : "a new line",
    "INDENTATION"                                                   : "an indentation",
    "EQUAL"                                                         : "an '=' literal",
    "END_IN_BLOCK"                                                  : "end in block",
    "LOCATION"                                                      : " a location statement",
    "REPEAT"                                                        : " a repeat statement",
    "REPEAT_TIMES"                                                  : " repeat times",
    "TRANSPORT"                                                     : " a transport statement",
    "FROM"                                                          : "a 'from'",
    "TO"                                                            : "a 'to'",
    "ON_DONE"                                                       : "an ondone statement",
    "TRIGGERED_BY"                                                  : "a triggered by",
    "FINISHED_BY"                                                   : "a finished by", 
    "COMMA"                                                         : " a ',' literal",
    "STARTS_WITH_LOWER_C_STR"                                       : "a String that starts with a lowercase char",
    "STARTS_WITH_UPPER_C_STR"                                       : "a String that starts with an uppercase char",
    "STRING_VALUE"                                                  : "a string value",
    "NUMERIC_VALUE"                                                 : "a number value",
    "EMPTY_VALUE"                                                   : "an empty value",
    "E_LEFT_PARENTHESIS"                                            : "a '{' literal",
    "E_RIGHT_PARENTHESIS"                                           : "a '}' literal",
    "E_LESS_THAN"                                                   : "a '<' literal",
    "E_LESS_THAN_OR_EQUAL"                                          : "a '<=' literal", 
    "E_GREATER_THAN"                                                : "a '>' literal",
    "E_GREATER_THAN_OR_EQUAL"                                       : "a '>=' literal",
    "E_EQUAL"                                                       : "a '= literal",
    "E_NOT_EQUAL"                                                   : "a '!=' literal",
    "E_BOOLEAN_AND"                                                 : "a '&&' literal",
    "E_BOOLEAN_OR"                                                  : "a '||' literal",
    "E_BOOLEAN_NOT"                                                 : "a '!' literal",
    "E_ATTRIBUTE"                                                   : "an attribute",
    "E_TRUE"                                                        : "a 'True' expression",
    "E_FALSE"                                                       : "a 'False' expression",
    "E_INTEGER"                                                     : "an integer value",
    "E_FLOAT"                                                       : "a float value",
}