name: Unit-Tests

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  unit-tests:

    # Set the type of machine to run on
    runs-on: ubuntu-latest
    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Setup Testing
        run: |
          sudo apt -qq update
          sudo apt -qq install -y graphviz
          ln -fs /usr/share/zoneinfo/Europe/Berlin /etc/localtime 
          pip3 install antlr4-python3-runtime tabulate snakes networkx matplotlib pandas scipy unittest-xml-reporting sqlalchemy --upgrade
          export PYTHONIOENCODING=utf-8

      - name: Test
        run: |
            python -m xmlrunner discover -s /lotlan_schedular/tests -v -o ./tmp/build/junit-reports
